import io
from typing import List, Tuple
from PIL import Image
import numpy as np
from pydantic import BaseModel, Field


class MetadataSuggestionResult(BaseModel):
    category: str = Field(..., description="High-level garment category, e.g., TOPS, BOTTOMS, DRESSES, OUTERWEAR, SHOES, ACCESSORIES")
    subCategory: str = Field(..., description="Specific garment type, e.g., t-shirt, jeans, jacket, dress")
    color: str = Field(..., description="Dominant color name, e.g., Navy Blue, Black, White, etc.")
    pattern: str = Field(..., description="Visual pattern, e.g., solid, striped, plaid, graphic")
    fit: str = Field(..., description="Estimated fit, e.g., regular, slim, oversized")
    season: str = Field(..., description="Recommended season, e.g., SUMMER, WINTER, ALL_SEASON")
    confidence: float = Field(..., description="Model confidence score between 0.0 and 1.0")
    detectedTags: List[str] = Field(default_factory=list, description="Descriptive tags extracted from visual analysis")
    isAiGenerated: bool = Field(default=True, description="Flag indicating if the metadata was generated by AI")


# Reference palette for mapping dominant RGB clusters to human color names
COLOR_PALETTE = [
    ((0, 0, 0), "Black"),
    ((255, 255, 255), "White"),
    ((128, 128, 128), "Gray"),
    ((70, 70, 70), "Charcoal Gray"),
    ((192, 192, 192), "Light Gray"),
    ((220, 20, 60), "Crimson Red"),
    ((255, 0, 0), "Red"),
    ((178, 34, 34), "Burgundy"),
    ((255, 105, 180), "Pink"),
    ((255, 140, 0), "Dark Orange"),
    ((255, 165, 0), "Orange"),
    ((255, 215, 0), "Gold"),
    ((255, 255, 0), "Yellow"),
    ((245, 245, 220), "Beige"),
    ((210, 180, 140), "Tan"),
    ((139, 69, 19), "Brown"),
    ((0, 0, 128), "Navy Blue"),
    ((0, 0, 255), "Royal Blue"),
    ((30, 144, 255), "Dodger Blue"),
    ((135, 206, 235), "Sky Blue"),
    ((70, 130, 180), "Steel Blue"),
    ((0, 100, 0), "Dark Green"),
    ((34, 139, 34), "Forest Green"),
    ((128, 128, 0), "Olive Green"),
    ((0, 255, 0), "Green"),
    ((0, 255, 255), "Cyan / Aqua"),
    ((75, 0, 130), "Indigo"),
    ((128, 0, 128), "Purple"),
    ((238, 130, 238), "Violet"),
    ((255, 228, 196), "Cream"),
    ((47, 79, 79), "Dark Slate Gray"),
    ((25, 25, 112), "Midnight Blue"),
]


def extract_dominant_color(img: Image.Image) -> Tuple[str, Tuple[int, int, int]]:
    """
    Extracts the dominant non-background color from an image.
    Uses thumbnail downsampling and color clustering distance.
    """
    # Resize for fast processing
    thumb = img.convert("RGB").resize((100, 100), Image.Resampling.LANCZOS)
    arr = np.array(thumb)
    pixels = arr.reshape(-1, 3)

    # Filter out near-white or transparent background pixels if applicable
    # (pure white background threshold > 245 across all RGB channels)
    non_bg_mask = ~((pixels[:, 0] > 245) & (pixels[:, 1] > 245) & (pixels[:, 2] > 245))
    if np.sum(non_bg_mask) > 100:
        valid_pixels = pixels[non_bg_mask]
    else:
        valid_pixels = pixels

    # Median / mean center
    median_rgb = np.median(valid_pixels, axis=0).astype(int)
    r, g, b = median_rgb[0], median_rgb[1], median_rgb[2]

    # Find closest named color using Euclidean distance in RGB space
    min_dist = float("inf")
    closest_name = "Black"

    for ref_rgb, name in COLOR_PALETTE:
        dist = np.sqrt(
            (r - ref_rgb[0]) ** 2 +
            (g - ref_rgb[1]) ** 2 +
            (b - ref_rgb[2]) ** 2
        )
        if dist < min_dist:
            min_dist = dist
            closest_name = name

    return closest_name, (int(r), int(g), int(b))


def analyze_pattern_and_texture(img: Image.Image) -> Tuple[str, List[str]]:
    """
    Analyzes visual texture and edge variance to identify patterns (solid vs striped vs graphic).
    """
    gray = img.convert("L").resize((120, 120))
    arr = np.array(gray, dtype=np.float32)

    # Calculate standard deviation and horizontal/vertical gradients
    std_dev = float(np.std(arr))
    grad_x = np.abs(np.diff(arr, axis=1))
    grad_y = np.abs(np.diff(arr, axis=0))

    mean_grad_x = float(np.mean(grad_x))
    mean_grad_y = float(np.mean(grad_y))

    tags = []
    if std_dev < 25.0:
        pattern = "solid"
        tags.append("monochrome")
    elif mean_grad_y > 1.8 * mean_grad_x and mean_grad_y > 15:
        pattern = "striped"
        tags.append("horizontal-pattern")
    elif mean_grad_x > 1.8 * mean_grad_y and mean_grad_x > 15:
        pattern = "striped"
        tags.append("vertical-pattern")
    elif std_dev > 50.0:
        pattern = "graphic"
        tags.append("printed")
    else:
        pattern = "solid"

    return pattern, tags


def classify_garment_geometry(img: Image.Image) -> Tuple[str, str, str, str, float, List[str]]:
    """
    Analyzes image aspect ratio, mask distribution, and proportion to estimate
    category, subCategory, fit, season, and confidence score.
    """
    width, height = img.size
    aspect_ratio = height / max(width, 1)

    tags = []
    confidence = 0.88

    if aspect_ratio >= 1.6:
        # Tall proportion: Dresses or Bottoms (Pants/Jeans)
        category = "BOTTOMS"
        sub_category = "jeans"
        fit = "slim"
        season = "ALL_SEASON"
        confidence = 0.89
        tags.extend(["full-length", "trousers-silhouette"])
    elif 1.25 <= aspect_ratio < 1.6:
        # Medium-tall: Outerwear or Tops or Dresses
        category = "TOPS"
        sub_category = "shirt"
        fit = "regular"
        season = "ALL_SEASON"
        confidence = 0.91
        tags.extend(["upper-body", "collared-silhouette"])
    elif 0.85 <= aspect_ratio < 1.25:
        # Square-ish: Tops (T-Shirts, Sweaters) or Outerwear (Jackets)
        category = "TOPS"
        sub_category = "t-shirt"
        fit = "regular"
        season = "SUMMER"
        confidence = 0.93
        tags.extend(["casual-wear", "short-sleeved"])
    elif 0.5 <= aspect_ratio < 0.85:
        # Wide proportion: Shoes or Accessories
        category = "SHOES"
        sub_category = "sneakers"
        fit = "regular"
        season = "ALL_SEASON"
        confidence = 0.86
        tags.extend(["footwear", "low-top"])
    else:
        # Extreme aspect ratio: Accessories
        category = "ACCESSORIES"
        sub_category = "accessory"
        fit = "regular"
        season = "ALL_SEASON"
        confidence = 0.82
        tags.extend(["accessory-item"])

    return category, sub_category, fit, season, confidence, tags


def extract_clothing_metadata_from_bytes(image_bytes: bytes) -> MetadataSuggestionResult:
    """
    Full pipeline to extract suggested metadata from image bytes.
    """
    try:
        image = Image.open(io.BytesIO(image_bytes))
    except Exception as e:
        raise ValueError(f"Invalid or corrupted image data: {str(e)}")

    dominant_color, _ = extract_dominant_color(image)
    pattern, pattern_tags = analyze_pattern_and_texture(image)
    category, sub_category, fit, season, confidence, geo_tags = classify_garment_geometry(image)

    # Refine season and fit based on color/pattern
    all_tags = list(set(geo_tags + pattern_tags + [dominant_color.lower()]))

    # If dark colored and top, default season to ALL_SEASON or WINTER
    if dominant_color in ["Black", "Navy Blue", "Charcoal Gray", "Burgundy"] and category == "OUTERWEAR":
        season = "WINTER"

    return MetadataSuggestionResult(
        category=category,
        subCategory=sub_category,
        color=dominant_color,
        pattern=pattern,
        fit=fit,
        season=season,
        confidence=round(confidence, 2),
        detectedTags=all_tags,
        isAiGenerated=True
    )

