import io
import time
import logging
from typing import Dict, Any, List
from PIL import Image, ImageDraw, ImageFont
import httpx

from app.services import storage

logger = logging.getLogger("ai-service.mock_vton")


async def generate_mock_tryon(
    job_id: str,
    user_id: str,
    avatar_url: str | None = None,
    garments: List[Dict[str, Any]] | None = None,
) -> Dict[str, Any]:
    """
    Generates a realistic mock virtual try-on composite image,
    uploads it to MinIO/S3 object storage, and returns the result key and URL.
    """
    start_time = time.time()
    width, height = 600, 800

    # 1. Base canvas (soft studio gradient)
    base_img = Image.new("RGB", (width, height), color=(245, 245, 247))
    draw = ImageDraw.Draw(base_img)

    # Gradient backdrop
    for y in range(height):
        r = int(240 - (y / height) * 20)
        g = int(242 - (y / height) * 18)
        b = int(248 - (y / height) * 15)
        draw.line([(0, y), (width, y)], fill=(r, g, b))

    # 2. Try fetching actual avatar image if accessible
    avatar_loaded = False
    if avatar_url:
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                resp = await client.get(avatar_url)
                if resp.status_code == 200:
                    avatar_raw = Image.open(io.BytesIO(resp.content)).convert("RGBA")
                    avatar_raw.thumbnail((width - 40, height - 120))
                    # Center avatar
                    offset_x = (width - avatar_raw.width) // 2
                    offset_y = 50
                    base_img.paste(avatar_raw, (offset_x, offset_y), avatar_raw)
                    avatar_loaded = True
        except Exception as e:
            logger.debug(f"Could not download avatar image from {avatar_url}: {e}")

    if not avatar_loaded:
        # Draw stylized model silhouette
        draw.ellipse([240, 100, 360, 220], fill=(210, 215, 225), outline=(180, 185, 195), width=2)  # Head
        draw.polygon([(220, 230), (380, 230), (410, 480), (190, 480)], fill=(195, 205, 220))  # Torso
        draw.rectangle([210, 490, 285, 720], fill=(170, 180, 200))  # Left leg
        draw.rectangle([315, 490, 390, 720], fill=(170, 180, 200))  # Right leg

    # 3. Render stylish Try-On UI overlay
    # Header badge
    draw.rounded_rectangle([20, 20, width - 20, 70], radius=10, fill=(30, 41, 59, 220))
    draw.text((35, 32), "AI VIRTUAL WARDROBE • TRY-ON RESULT", fill=(255, 255, 255))
    draw.text((width - 170, 34), f"JOB: {job_id[:8]}", fill=(148, 163, 184))

    # Garment items breakdown at bottom
    if garments:
        garment_count = len(garments)
        draw.rounded_rectangle([20, height - 120, width - 20, height - 20], radius=10, fill=(255, 255, 255))
        draw.text((35, height - 110), f"OUTFIT ITEMS ({garment_count}):", fill=(71, 85, 105))

        x_pos = 35
        for i, g in enumerate(garments[:4]):
            cat = g.get("category", "ITEM").upper()
            sub = g.get("subcategory") or ""
            label = f"• {cat}" + (f" ({sub})" if sub else "")
            draw.text((x_pos, height - 85), label, fill=(15, 23, 42))
            x_pos += 140

    # Watermark footer
    draw.text((35, height - 45), "Generated by Virtual Wardrobe VTON Engine (Mock Mode)", fill=(100, 116, 139))

    # 4. Save to buffer
    buffer = io.BytesIO()
    base_img.save(buffer, format="JPEG", quality=90)
    img_bytes = buffer.getvalue()

    # 5. Upload to S3
    result_key = f"tryon/{user_id}/{job_id}.jpg"
    storage.upload_bytes(img_bytes, result_key, content_type="image/jpeg")
    result_url = storage.get_object_url(result_key)

    elapsed_ms = int((time.time() - start_time) * 1000)
    logger.info(f"Generated mock try-on in {elapsed_ms}ms: {result_key}")

    return {
        "result_image_key": result_key,
        "result_image_url": result_url,
        "processing_time_ms": elapsed_ms,
    }

